//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHLabel {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class InstallScript : global::System.Configuration.ApplicationSettingsBase {
        
        private static InstallScript defaultInstance = ((InstallScript)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InstallScript())));
        
        public static InstallScript Default {
            get {
                return defaultInstance;
            }
        }
    }
}
